version: "3.7"


networks:
  net-alice-kms:
  net-alice:
  net-bob:
  net-public:

services:
  kms-alice:
    command: start --config /root/tmkms/tmkms.toml
    container_name: kms-alice
    image: tmkms_i:v0.12.2
    volumes:
      - ./docker/kms-alice:/root/tmkms
    networks:
      - net-alice-kms

  val-alice:
    command: start
    container_name: val-alice
    depends_on:
      - kms-alice
    image: checkersd_i
    volumes:
      - ./docker/val-alice:/root/.checkers
    networks:
      - net-alice-kms
      - net-alice

  sentry-alice:
    command: start
    container_name: sentry-alice
    image: checkersd_i
    volumes:
      - ./docker/sentry-alice:/root/.checkers
    networks:
      - net-alice
      - net-public

  val-bob:
    command: start
    container_name: val-bob
    image: checkersd_i
    volumes:
      - ./docker/val-bob:/root/.checkers
    networks:
      - net-bob
  
  sentry-bob:
    command: start
    container_name: sentry-bob
    image: checkersd_i
    volumes:
      - ./docker/sentry-bob:/root/.checkers
    networks:
      - net-bob
      - net-public

  node-carol:
    command: start
    container_name: node-carol
    image: checkersd_i
    volumes:
      - ./docker/node-carol:/root/.checkers
    networks:
      - net-public
    ports:
      - 0.0.0.0:26657:26657